# .github/workflows/test.yml
name: ML Pipeline Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest tests/ -v

    - name: Run linters
      run: |
        pip install flake8 bandit
        flake8 src/ --max-line-length=88 --exclude=__init__.py
        bandit -r src/ -x tests/

    - name: Security audit
      run: |
        pip install pip-audit
        pip-audit|| true

    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        to: hludneva.valeria@gmail.com
        from: GitHub Actions
        subject: "Tests ${{ job.status }}: ${{ github.workflow }}"
        body: |
          Repository: ${{ github.repository }}
          Workflow: ${{ github.workflow }}
          Status: ${{ job.status }}
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Triggered by: ${{ github.actor }}

          View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  docker-security:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Trivy security scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'
